- hosts: k8s
  become: yes

  vars:
    domain: example.local
    network:
      int_iface: eth1
      ext_iface: eth0
      generate_hostfile: no
      vx_lan_network: 172.30.0.0/16
      vx_lan_subnet_len: 24

    dashboard: yes

  roles:
  - name: Prepare hosts with requirements
    role: k8s-common

  - name: Prepare master nodes
    role: k8s-master
    when: inventory_hostname in groups['k8s-master']

  - name: Prepare kubelet nodes
    role: k8s-node
    when: inventory_hostname in groups['k8s-node']
