- name: Install kubernetes packages
  yum: name={{item}}  state=present
  with_items:
  - docker
  - kubernetes
  - flannel

- name: Create folder for certificates
  file: path={{item}} state=directory mode="u=rwX,g=rX,o=rX"
  with_items:
  - "{{kube_certs_dir}}"
  - "{{etcd_certs_dir}}"
  tags: certs

- name: Copy CA cert all nodes
  copy:
    src: "{{cert_ca_dir_tmp}}/{{item}}/ca.pem"
    dest: "{{k8s_cert_dir}}/{{item}}/ca.pem"
    owner: root
    group: root
    mode: 0644
  with_items:
  - kubernetes
  - etcd
  tags: certs

- name: Copy own certs
  copy:
    src: "{{cert_ca_dir_tmp}}/{{item}}"
    dest: "{{k8s_cert_dir}}/{{item}}"
    owner: root
    group: root
    mode: 0644
  with_items:
  - "etcd/{{inventory_hostname}}.pem"
  - "etcd/{{inventory_hostname}}-key.pem"
  - "kubernetes/{{inventory_hostname}}.pem"
  - "kubernetes/{{inventory_hostname}}-key.pem"
  tags:
  - certs
  - etcd

- name: Generate /etc/sysconfig/flanneld
  template: src=etc/sysconfig/flanneld.j2 dest=/etc/sysconfig/flanneld backup=yes
  tags: flannel
  notify:
  - restart flanneld service

- name: Start and enable flanneld
  service: name=flanneld state=restarted enabled=yes
  tags: flannel

- name: Generate /etc/kubernetes/kubelet
  template: src=etc/kubernetes/kubelet.j2 dest=/etc/kubernetes/kubelet
  tags: kubelet

- name: Generate kubelet kubeconfig
  template: src=kubeconfig.j2 dest={{kubelet_kubeconfig}}
  tags: kubelet

- name: Fix docker log-driver option
  lineinfile:
    regexp: "^OPTIONS="
    line: OPTIONS='--signature-verification=false'
    dest: /etc/sysconfig/docker
  tags: kubelet

- name: Start {{item}} service
  service: name={{item}} state=restarted enabled=yes
  with_items:
  - kubelet
  - flanneld
  - docker
  tags: [ kubelet, flanneld, docker ]
