- name: Disable selinux
  selinux: state=disabled
  tags:
  - selinux
  - config
  - security

- name: Disable firewall
  service: name={{item}} state=stopped enabled=false
  with_items:
  - iptables-services
  - firewalld
  ignore_errors: yes
  tags:
  - config
  - firewall
  - security

- name: Install base packages
  yum: name={{item}}  state=present
  with_items: "{{base_packages}}"
  tags: ntp

- name: set timezone to {{timezone}}
  command: timedatectl set-timezone {{timezone}}
  tags: ntp

- name: setup ntp server
  lineinfile: regexp="^server" line="server {{item}} iburst" dest=/etc/ntp.conf backup=yes
  with_items: "{{ntp_servers}}"
  notify: restart ntp
  tags:
  - ntp
  - config

- name: sync time and hwclock
  shell: systemctl stop ntpd && ntpdate {{ntp_servers[0]}} && hwclock -w && systemctl start ntpd
  tags:
  - ntp

- name: start and enable ntp server
  service: name=ntpd enabled=yes
  tags: ntp

- name: Generate /etc/hosts file
  template:
    src=etc/hosts.j2
    dest=/etc/hosts
  tags:
  - hosts
  - config
