- name : Set machine hostname
  hostname: name="{{inventory_hostname}}"

- name: Generate /etc/hosts file
  template:
    src=etc/hosts.j2
    dest=/etc/hosts
  tags:
  - hosts
  - config

- name: Include security configurations
  include: security.yml
  tags: security

- name: Install base packages
  yum: name={{item}}  state=present
  with_items: "{{base_packages}}"
  tags: ntp

- name: set timezone to {{timezone}}
  command: timedatectl set-timezone {{timezone}}
  tags: ntp

- name: setup ntp server
  lineinfile: regexp="^server" line="server {{item}} iburst" dest=/etc/chrony.conf backup=yes
  with_items: "{{ntp_servers}}"
  notify: restart chrony
  tags: ntp

- meta: flush_handlers
