- name: Generate /etc/etcd/etcd.conf
  template: src=etc/etcd/etcd.conf.j2 dest=/etc/etcd/etcd.conf
  tags: etcd

- name: Generate /etc/kubernetes/apiserver
  template: src=etc/kubernetes/apiserver.j2 dest=/etc/kubernetes/apiserver
  tags: kubernetes

- name: Start Etcd service
  service: name=etcd state=started enabled=yes
  tags: etcd

- name: Copy etcd-init.sh script in /tmp
  template: src=etcd-init.sh.j2 dest=/tmp/etcd-init.sh mode=750

- name: Run etcd-init.sh script
  command: /tmp/etcd-init.sh > /tmp/etcd-init.log 2>&1
  register: etcd_init
  failed_when: >
    etcd_init.rc != 0 and ("Key already exists" not in etcd_init.stderr)

- name: Config flannel network overlay
  template: src=etc/sysconfig/flanneld.j2 dest=/etc/sysconfig/flanneld
  tags: flanneld

- name: Start {{item}} service
  service: name={{item}} state=restarted enabled=yes
  with_items:
  - etcd
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler
  - flanneld
  tags: [ etcd, kubernetes, flanneld]
