- set_fact: nfs_server={{ ansible_hostname }}

- name: Install NFS server
  yum: name=nfs-utils state=installed

- name: Configure export
  template: src=etc/exports.j2 dest=/etc/exports

- name: Create exports dir
  file: dest=/exports state=directory mode=755 owner=nobody group=nobody

- name: Start NFS service
  service: name=nfs state=started enabled=yes
