  - name: Add kubernetes repo
    yum_repository:
      name: virt7-docker-common-release
      description: virt7-docker-common-release
      file: virt7-docker-common-release
      baseurl: http://cbs.centos.org/repos/virt7-docker-common-release/x86_64/os/
      gpgcheck: no
      enabled: no

  - name: Install base packages
    yum: name={{item}} enablerepo=virt7-docker-common-release  state=latest
    with_items:
    - kubernetes
    - etcd
    - flannel

  - name: Generate /etc/hosts file
    template:
      src=etc/hosts.j2
      dest=/etc/hosts
    when: network.generate_hostfile
    tags: hosts

  - name: Generate /etc/kubernetes/config file
    template:
      src=etc/kubernetes/config.j2
      dest=/etc/kubernetes/config
    tags: kubernetes

  - name: Disable firewall
    service: name={{item}} state=stopped enabled=false
    with_items:
    - iptables-services
    - firewalld
    ignore_errors: yes
    tags: conf
